version: '3.8'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/workspace
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - common
networks:
  common:
    name: common
    driver: bridge