services:
  primary:
    container_name: ddb-primary
    image: postgres-14
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - ddb-network
    stdin_open: true
    tty: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  standby:
    container_name: ddb-standby
    image: postgres-14
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5433:5433"
    networks:
      - ddb-network
    stdin_open: true
    tty: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  ddb-network:
    driver: bridge